### ISSUE TITLE
enhancement suggestion

### ISSUE THREAD

**Issue by itslemcy** [6XGate/bridgecmdr#23]
could it be possible to configure everything also from a computer? like if i access the ip address i can edit the sources, switches and tiles from my laptop's browser?

**Comment by 6XGate** [comment]
This would be a far off feature since the current design does not have a server back-end.  I'll consider it though.

**Comment by itslemcy** [comment]
> This would be a far off feature since the current design does not have a server back-end. I'll consider it though.
It could be really comfy if you could change the input from your couch on your phone :)

**Comment by the0remora** [comment]
@itslemcy when I was setting mine up I used VNC. This should also work fine from a Phone/Tablet. It's not as elegant as using a webpage but is functional.

Also as a note for @6XGate I am running my setup on a 3B and it works fine. Although I did use my 4 to set it up, to much lag on the 3B. Although now that I have everything added it has no issues changing ties around.

**Comment by 6XGate** [comment]
I foresee the only way in the future for this to work that way is to use tRPC so express and Electron can both use the main process for native system interaction. Might be a v3 thing since v2 is focusing on updating the UI to Vue 3 and Vuetify 3 with better flow and proper IPC support for Electorn.

**Comment by 6XGate** [comment]
This will be track by #92.
