### ISSUE TITLE
enhancement: make the icons arrangeable

### ISSUE THREAD

**Issue by itslemcy** [6XGate/bridgecmdr#27]
could it be possible to make the icons arrangeable and scalable? I am using a larger touchscreen and that would be cool! thanks :)

**Comment by 6XGate** [comment]
For rearranging the icons, I've considered this; I can slate if for a future release.  As for resizing it, that could be a small ask to implement. So I might add that to a near future milestone.

**Comment by 6XGate** [comment]
v2.0.0-beta.6 allows you to change the icon sizes. Be sure to get v1.3.0 to export your current settings to import in v2.
